name: to_do
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+11

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^20.1.0
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  in_app_review: ^2.0.11
  intl: ^0.20.2
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  timezone: ^0.10.1
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  isar_community_generator: ^3.3.0
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true
  generate: true

